import "./globals.css";
import type { Metadata } from "next";
import { Karla, Caveat_Brush } from "next/font/google";

const karla = Karla({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-karla",
});

const share = Caveat_Brush({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-share",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={`${karla.variable} ${share.variable}`}>
      <body className={`bg-zinc-50`}>{children}</body>
    </html>
  );
}
